# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.decomposition import PCA
from scipy.cluster.hierarchy import dendrogram, linkage

import datetime as dt

from google.colab import files
uploaded = files.upload()

df = pd.read_excel("/content/online_retail_II.xlsx")

df.head()

df.info()

# Remove missing customer IDs
df = df.dropna(subset=['Customer ID'])

# Remove returns or invalid values
df = df[df['Quantity'] > 0]
df = df[df['Price'] > 0]

# Convert date column
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df.head()

df['TotalPrice'] = df['Quantity'] * df['Price']

df.head()

reference_date = df['InvoiceDate'].max() + dt.timedelta(days=1)

recency = df.groupby('Customer ID')['InvoiceDate'].max()
recency = (reference_date - recency).dt.days

frequency = df.groupby('Customer ID')['Invoice'].nunique()

monetary = df.groupby('Customer ID')['TotalPrice'].sum()

rfm = pd.DataFrame({
    'Recency': recency,
    'Frequency': frequency,
    'Monetary': monetary
})

rfm.head()

scaler = StandardScaler()

rfm_scaled = scaler.fit_transform(rfm)

rfm_scaled[:5]

wcss = []

for i in range(1,11):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(rfm_scaled)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(8,5))
plt.plot(range(1,11), wcss, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42)

rfm['Cluster'] = kmeans.fit_predict(rfm_scaled)

rfm.head()

rfm.groupby('Cluster').mean()

linked = linkage(rfm_scaled, method='ward')

plt.figure(figsize=(10,6))
dendrogram(linked)
plt.title("Hierarchical Clustering")
plt.show()

hc = AgglomerativeClustering(n_clusters=4)

rfm['HC_Cluster'] = hc.fit_predict(rfm_scaled)

rfm.head()

dbscan = DBSCAN(eps=0.8, min_samples=5)

rfm['DBSCAN_Cluster'] = dbscan.fit_predict(rfm_scaled)

rfm.head()

pca = PCA(n_components=2)

pca_features = pca.fit_transform(rfm_scaled)

rfm['PCA1'] = pca_features[:,0]
rfm['PCA2'] = pca_features[:,1]

rfm.head()

plt.figure(figsize=(8,6))

sns.scatterplot(
    x='PCA1',
    y='PCA2',
    hue='Cluster',
    palette='Set2',
    data=rfm
)

plt.title("Customer Segmentation (KMeans)")
plt.show()

cluster_summary = rfm.groupby('Cluster').mean()

print(cluster_summary)

!pip install streamlit pyngrok pandas numpy matplotlib seaborn scikit-learn openpyxl scipy

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# 
# from sklearn.preprocessing import StandardScaler
# from sklearn.cluster import KMeans
# from sklearn.decomposition import PCA
# import datetime as dt
# 
# st.title("Online Retail Customer Segmentation")
# 
# st.write("Upload the Online Retail dataset")
# 
# uploaded_file = st.file_uploader("Upload Excel File", type=["xlsx"])
# 
# if uploaded_file:
# 
#     df = pd.read_excel(uploaded_file)
# 
#     st.subheader("Dataset Preview")
#     st.write(df.head())
# 
#     # Cleaning
#     df = df.dropna(subset=['CustomerID'])
#     df = df[df['Quantity'] > 0]
#     df = df[df['UnitPrice'] > 0]
# 
#     df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
# 
#     # Feature Engineering
#     df['TotalPrice'] = df['Quantity'] * df['UnitPrice']
# 
#     reference_date = df['InvoiceDate'].max() + dt.timedelta(days=1)
# 
#     recency = df.groupby('CustomerID')['InvoiceDate'].max()
#     recency = (reference_date - recency).dt.days
# 
#     frequency = df.groupby('CustomerID')['InvoiceNo'].nunique()
# 
#     monetary = df.groupby('CustomerID')['TotalPrice'].sum()
# 
#     rfm = pd.DataFrame({
#         'Recency': recency,
#         'Frequency': frequency,
#         'Monetary': monetary
#     })
# 
#     st.subheader("RFM Table")
#     st.write(rfm.head())
# 
#     # Scaling
#     scaler = StandardScaler()
#     rfm_scaled = scaler.fit_transform(rfm)
# 
#     # KMeans
#     kmeans = KMeans(n_clusters=4, random_state=42)
#     rfm['Cluster'] = kmeans.fit_predict(rfm_scaled)
# 
#     st.subheader("Cluster Summary")
#     st.write(rfm.groupby('Cluster').mean())
# 
#     # PCA Visualization
#     pca = PCA(n_components=2)
#     pca_features = pca.fit_transform(rfm_scaled)
# 
#     rfm['PCA1'] = pca_features[:,0]
#     rfm['PCA2'] = pca_features[:,1]
# 
#     fig, ax = plt.subplots()
# 
#     sns.scatterplot(
#         x='PCA1',
#         y='PCA2',
#         hue='Cluster',
#         palette='Set2',
#         data=rfm
#     )
# 
#     plt.title("Customer Segments")
# 
#     st.pyplot(fig)

!npm install localtunnel

!streamlit run app.py &>/content/logs.txt &

